### ISSUE TITLE
Hide the password from the menu

### ISSUE THREAD

**Issue by antoyo** [carnager/rofi-pass#53] opened 2016-08-19 02:03 UTC
Hello.
Currently, the password is shown in the menu, but I would like to hide it.
Is there an option to never show the password in the menu?
Thanks.

**Comment by carnager** [comment] 2016-08-19 13:30
hmm? There is no password shown in menu. Except for the "Show Menu" which name includes the word "Show" for a reason...

**Comment by antoyo** [comment] 2016-08-19 13:51
Is the "Show Menu" shown when I press enter after selecting the password?
When I press enter, I see:
* Choose Field to type >
* autotype
* user
* pass
* (and the actual password)

So, is it the normal behavior?
Does this mean that I must use the shortcuts (for instance, `Alt+1`) to autotype without ever seeing the password?
Thanks for your answer.

**Comment by carnager** [comment] 2016-08-19 13:58
i cant reproduce this at all... can you create a fake password file, run bash -x /path/to/rofi-pass, hit enter and show the output?

fake password file to protect your sensitive data

**Comment by carnager** [comment] 2016-08-19 14:12
just tried with spaces in passwords. cant reproduce. Are you on master branch btw?
And yes, I would like the logs

**Comment by antoyo** [comment] 2016-08-19 14:22
I use [the version 1.4.1 from the ArchLinux User Repository](https://aur.archlinux.org/packages/rofi-pass/).
[I attached the logs here.](https://github.com/carnager/rofi-pass/files/427179/pass_logs.txt)
Thanks for your help.

**Comment by carnager** [comment] 2016-08-19 14:26
can you try -git?

**Comment by antoyo** [comment] 2016-08-19 14:43
I cloned this repository to test the git version and it does not show the password.
So, that solves my issue.
Thanks.

**Comment by carnager** [comment] 2016-08-19 14:48
fixed in 1.4.2. https://github.com/carnager/rofi-pass/releases/tag/1.4.2

**Closed by carnager** 2016-08-19 14:48 UTC
